import Link from 'next/link';
import { SITE } from '@/lib/site';
import { StoreButtons } from '@/components/StoreButtons';
import { TrustBadgeRow } from '@/components/TrustBadgeRow';
import { ComparisonTable } from '@/components/ComparisonTable';
import { PricingToggle } from '@/components/PricingToggle';
import { MobileApplicationSchema } from '@/components/schema/MobileApplication';
import { FAQPageSchema } from '@/components/schema/FAQPage';
import { getLiveArticles } from '@/lib/articles';

// Homepage — per build brief §3.1: ONE canonical hero paragraph, ONE drug line, ONE default price in SSR.
// Currency toggle is client-only; inactive variants do not exist in the initial HTML.

const homepageFaq = [
  {
    q: 'Is Muscle Guard a medical device?',
    a: 'No. Muscle Guard is a self-tracking companion and coach for people on GLP-1 medications. It is not a medical device and does not provide medical advice. Always consult your healthcare provider for medical decisions.',
  },
  {
    q: 'Which GLP-1 medications does Muscle Guard support?',
    a: 'Ozempic and Wegovy (semaglutide), Mounjaro and Zepbound (tirzepatide), Rybelsus (oral semaglutide), Saxenda (liraglutide), plus compounded semaglutide and tirzepatide preparations. The app knows the standard titration schedule for each.',
  },
  {
    q: 'Why does muscle preservation matter on a GLP-1?',
    a: 'GLP-1 medications suppress appetite so effectively that many users enter a severe calorie and protein deficit. Without intervention, 25 to 40 percent of total weight lost can be lean muscle, not fat. Adequate protein (1.2 to 1.6 g per kg per day) plus resistance training drops that figure substantially.',
  },
  {
    q: 'How much does Muscle Guard cost?',
    a: 'Free forever for the basics. Pro is R99 per month or R899 per year (approximately USD 5.99 / EUR 5.99 / GBP equivalents) with a 7-day free trial — no card needed to start.',
  },
];

export default function HomePage() {
  const features = [
    { icon: '★', title: 'Muscle Guard Score', hero: true, body: 'The hero metric. Combines protein adherence, resistance training, weight trend and body composition into one number that captures fat loss without muscle loss.' },
    { icon: '⌂', title: 'Privacy first', hero: true, body: 'Delete your account in one tap, all data is gone. No cookie banner. No third-party trackers. POPIA, GDPR and CCPA-ready.' },
    { icon: '💉', title: 'Injection & tablet tracking', hero: false, body: 'Knows the standard titration schedule for every approved GLP-1 — including Rybelsus oral pill and compounded vials.' },
    { icon: '📷', title: 'AI plate scan', hero: false, body: 'Snap your meal — get macros, protein target progress, and a quick logging interface. Powered by Open Food Facts + Google Gemini, transparently disclosed.' },
    { icon: '🤖', title: 'Personal Coach', hero: false, body: 'Pattern detection across symptoms, mood and logs. Spots stalls, side-effect clusters and protein gaps before they derail your journey.' },
    { icon: '📄', title: 'Clinical Report export', hero: false, body: 'A branded one-page report you can hand your doctor at your next visit. Generated by you, on your terms — not 12 weeks of WhatsApp screenshots.' },
    { icon: '📸', title: 'Progress photos', hero: false, body: 'Built-in pose guide, side-by-side compare, monthly reminders. Comparable photos that tell the truth.' },
    { icon: '📊', title: 'Body composition', hero: false, body: 'Waist, hip, neck, body-fat estimate, visceral-fat rating. The numbers that prove muscle is being preserved while fat is lost.' },
    { icon: '🏆', title: 'Plateau Breaker', hero: false, body: 'A 14-day metabolic reset protocol when the scale stalls. Adjusts macros and training so you stop chasing the same approach that just stopped working.' },
  ];

  const liveArticles = getLiveArticles().slice(0, 4);

  return (
    <>
      <MobileApplicationSchema />
      <FAQPageSchema items={homepageFaq} />

      {/* HERO — canonical single version per build brief §3.1 */}
      <section
        className="py-16 md:py-20"
        style={{ background: 'linear-gradient(180deg, var(--brand-green-bg) 0%, white 100%)' }}
      >
        <div className="wrap">
          <div className="grid items-center gap-14 md:grid-cols-[1.1fr_1fr]">
            <div>
              <h1 className="mb-2">
                {SITE.hero.h1Part1}{' '}
                <span className="text-brand-green">{SITE.hero.h1Part2}</span>
              </h1>
              <p className="my-7 max-w-[42ch] text-[17px] text-muted">{SITE.hero.body}</p>
              <p className="my-3 text-[14px] text-muted">
                <strong>Built for:</strong> {SITE.hero.builtFor}
              </p>
              <div className="my-6">
                <StoreButtons />
              </div>
              <p className="mt-5 text-[13px] text-muted">{SITE.hero.priceLine}</p>
              <TrustBadgeRow />
            </div>

            <div>
              <div className="rounded-3xl border border-rule bg-white p-8 shadow-mockup">
                <div className="mb-1 text-[11px] uppercase tracking-[1.5px] text-muted">Muscle Guard Score</div>
                <div className="relative mx-auto my-3 grid h-[180px] w-[180px] place-items-center">
                  <svg viewBox="0 0 180 180" className="absolute inset-0" aria-hidden="true">
                    <circle cx="90" cy="90" r="76" fill="none" stroke="#E8F4F1" strokeWidth="10" />
                    <circle
                      cx="90"
                      cy="90"
                      r="76"
                      fill="none"
                      stroke="#0F7B6C"
                      strokeWidth="10"
                      strokeDasharray="380"
                      strokeDashoffset="95"
                      strokeLinecap="round"
                      transform="rotate(-90 90 90)"
                    />
                  </svg>
                  <div className="relative text-center">
                    <div className="text-[48px] font-semibold text-brand-green">78</div>
                    <div className="text-[11px] uppercase tracking-[1px] text-muted">Excellent</div>
                  </div>
                </div>
                <div className="mt-6 text-[11px] uppercase tracking-[1.5px] text-muted">This week&apos;s check-ins</div>
                <div className="mt-3 grid grid-cols-6 gap-2">
                  {['on', 'on', 'on', 'on', 'partial', 'on'].map((s, i) => (
                    <div
                      key={i}
                      className="aspect-square rounded-full border"
                      style={{
                        background: s === 'on' ? '#0F7B6C' : s === 'partial' ? '#C97E1A' : '#E8F4F1',
                        borderColor: s === 'on' ? '#0F7B6C' : s === 'partial' ? '#C97E1A' : '#E5E7E6',
                      }}
                    />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FEATURES — 9 cards */}
      <section id="features" className="py-20">
        <div className="wrap">
          <div className="mx-auto mb-12 max-w-3xl text-center">
            <div className="eyebrow eyebrow-green mb-3">Built around muscle preservation</div>
            <h2 className="mb-3">Everything you need on a GLP-1, in one app</h2>
            <p className="text-[17px] text-muted">
              Nine features, all working together. Track every drug, every metric, every milestone — built for fat loss without muscle loss.
            </p>
          </div>
          <div className="grid gap-5 md:grid-cols-3">
            {features.map((f) => (
              <div key={f.title} className={`feature ${f.hero ? 'feature-hero' : ''}`}>
                <div className="feature-icon">{f.icon}</div>
                <h3 className="mb-2 text-[17px]">{f.title}</h3>
                <p className="text-[14px] text-muted">{f.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* COMPARISON */}
      <section id="comparison" className="bg-brand-green-bg py-20">
        <div className="wrap">
          <div className="mx-auto mb-12 max-w-3xl text-center">
            <div className="eyebrow mb-3">The category</div>
            <h2 className="mb-3">Muscle Guard vs the category</h2>
            <p className="text-[17px] text-muted">
              The features that make Muscle Guard the only GLP-1 companion built around what you&apos;re keeping, not just what you&apos;re losing.
            </p>
          </div>
          <ComparisonTable />
        </div>
      </section>

      {/* DIFFERENTIATOR / mechanism */}
      <section className="py-20">
        <div className="wrap">
          <div className="mx-auto mb-12 max-w-3xl text-center">
            <div className="eyebrow mb-3">The differentiator</div>
            <h2 className="mb-3">How muscle preservation works on a GLP-1</h2>
            <p className="text-[17px] text-muted">
              The concern that surfaces in every Reddit thread and every clinical paper — and the only one we put in the headline.
            </p>
          </div>
          <div className="mx-auto max-w-prose text-[16px]">
            <p className="mb-4">
              GLP-1 medications suppress appetite so effectively that many users enter a severe calorie and protein deficit. Muscle is built from protein, so a sustained deficit can lead to loss of lean mass — what users call &ldquo;muscle drain&rdquo; or &ldquo;Ozempic face.&rdquo;
            </p>
            <p className="mb-4">
              The prevention plan is well-established: aim for{' '}
              <strong>1.2 to 1.6 g of protein per kg of body weight per day</strong> (about 90 to 120 g for many adults), perform{' '}
              <strong>resistance training 2 to 4 times per week</strong>, avoid extreme calorie restriction, and track strength and body composition — not just weight.
            </p>
            <p className="mb-4">
              Muscle Guard is built around that plan. Every feature, every milestone, every metric is in service of one thing: fat loss without muscle loss.
            </p>
            <p className="mt-8 text-center">
              <Link className="btn" href="/research/glp1-and-muscle-loss/">
                Read the full muscle-preservation guide →
              </Link>
            </p>
          </div>
        </div>
      </section>

      {/* FIELD NOTES — surfaces live research */}
      {liveArticles.length > 0 && (
        <section className="bg-bg py-20">
          <div className="wrap">
            <div className="mx-auto mb-12 max-w-3xl text-center">
              <div className="eyebrow eyebrow-green mb-3">Field notes</div>
              <h2 className="mb-3">The research, in plain English</h2>
              <p className="text-[17px] text-muted">
                A free, cited library of evidence on GLP-1s and muscle. Updated when the science updates.
              </p>
            </div>
            <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
              {liveArticles.map((a) => (
                <Link
                  key={a.slug}
                  href={`/research/${a.slug}/`}
                  className="block rounded-card border border-rule bg-white p-6 no-underline transition hover:border-brand-green"
                >
                  <div className="mb-3 text-[12px] uppercase tracking-[1px] text-muted">
                    {a.dateModified}
                  </div>
                  <h3 className="mb-2 text-[17px] text-ink">{a.title}</h3>
                  <p className="text-[14px] text-muted">{a.description}</p>
                </Link>
              ))}
            </div>
            <div className="mt-10 text-center">
              <Link className="btn btn-outline" href="/research/">
                See all research →
              </Link>
            </div>
          </div>
        </section>
      )}

      {/* PRICING */}
      <section id="pricing" className="py-20">
        <div className="wrap">
          <div className="mx-auto mb-12 max-w-3xl text-center">
            <div className="eyebrow eyebrow-green mb-3">Pricing</div>
            <h2 className="mb-3">Free to start. Pro covers what AI costs us.</h2>
            <p className="text-[17px] text-muted">Honest pricing. No card needed for the 7-day Pro trial.</p>
          </div>
          <div className="text-center">
            <PricingToggle />
          </div>
          <div className="mx-auto mt-10 max-w-3xl rounded-lg border-l-4 border-gold bg-gold-bg p-5 text-[14px]">
            <strong className="text-gold">AI cost transparency.</strong> Plate scan, Personal Coach and Gemini-powered features cost us money per request. Pro covers that and keeps the app honest. We will never sell your data to subsidise free AI.
          </div>
        </div>
      </section>

      {/* DOWNLOAD CTA */}
      <section id="download" className="bg-brand-green py-20 text-white">
        <div className="wrap text-center">
          <div className="eyebrow mb-3" style={{ color: 'rgba(255,255,255,0.85)' }}>Get started</div>
          <h2 className="mb-3 text-white">Start your GLP-1 journey strong</h2>
          <p className="mb-8 text-white/85">Free to download. 7-day Pro trial. Cancel anytime. No card needed.</p>
          <div className="flex justify-center">
            <StoreButtons variant="light" />
          </div>
        </div>
      </section>
    </>
  );
}
